'use client';

/**
 * Marketing home page for the white-label DEMO brand (Lionheart Appraisal),
 * rendered at /site (EN) and /site/fr (FR) with the copy object swapped.
 *
 * Art direction: automotive-retail landing language (light warm-grey studio
 * hero, one script accent word, floating pill nav, car photography bleeding
 * off-frame with a floating file card, radiating callouts around the
 * top-view vehicle diagram, split contact banner). Scroll parallax on the
 * imagery layers; reveal-on-scroll on copy. Both respect reduced motion.
 *
 * Assets: public/site/hero-car.webp + car-side.webp (generated studio shots of
 * one consistent sedan), public/site/shots/*.webp (real app screenshots,
 * regenerated by scripts/site-shots.mjs + scripts/site-images.mjs).
 */

import React from 'react';
import Link from 'next/link';
import {
  ScanSearch,
  MapPin,
  FileSignature,
  BellRing,
  History,
  ShieldCheck,
  Languages,
  UserRoundCheck,
  ArrowRight,
  Camera,
  Gauge,
  ListChecks,
  GitBranch,
  FileText,
  Navigation,
  Layers,
  CarFront,
} from 'lucide-react';
import CarSvgTop from '@/components/car-svg-top';
import { SCRIPT } from './chrome';
import type { HomeCopy } from './home-copy';

type IconType = React.ComponentType<{ className?: string; 'aria-hidden'?: boolean }>;

// Icons are layout, not copy: they stay here and are zipped with the text.
const STEP_ICONS: IconType[] = [ScanSearch, Navigation, FileSignature];
const DESK_ICONS: IconType[] = [ScanSearch, BellRing, History];
const CALLOUT_LEFT_ICONS: IconType[] = [CarFront, Camera, Gauge];
const CALLOUT_RIGHT_ICONS: IconType[] = [ListChecks, GitBranch, FileText];
const TRUST_ICONS: IconType[] = [ShieldCheck, UserRoundCheck, History, Languages];
const CHIP_ICONS: IconType[] = [MapPin, Camera, Layers, FileText, ListChecks];

const DEMO_CTA = 'plausible-event-name=Open+demo';

export function HomePage({ copy }: { copy: HomeCopy }) {
  const c = copy;
  return (
    <main id="top" lang={c.locale}>
      {/* Hero */}
      <section data-parallax-scope className="relative overflow-hidden pt-32 sm:pt-40">
        <div aria-hidden className="site-grain pointer-events-none absolute inset-0 opacity-[.35] mix-blend-multiply" />
        <div aria-hidden className="site-dots pointer-events-none absolute right-[-2rem] top-24 h-56 w-72 opacity-70 [mask-image:radial-gradient(closest-side,#000,transparent)]" />
        <div aria-hidden data-parallax="0.35" className="pointer-events-none absolute -left-40 bottom-[-14rem] h-[30rem] w-[30rem] rounded-full bg-[var(--teal-soft)] opacity-70" />

        <div className="relative mx-auto max-w-6xl px-4 sm:px-6">
          <h1
            data-reveal
            className="mx-auto max-w-4xl text-center text-[2.6rem] font-bold leading-[1.02] tracking-[-0.02em] sm:text-[4.2rem] lg:text-[5rem]"
          >
            {c.hero.h1a}{' '}
            <span className="font-normal text-[var(--accent)]" style={{ fontFamily: SCRIPT, fontSize: '1.34em', lineHeight: 1, letterSpacing: 0 }}>
              {c.hero.accent}
            </span>
            <br className="hidden sm:block" /> {c.hero.h1b}
          </h1>
          <p data-reveal data-reveal-delay="1" className="mx-auto mt-6 max-w-xl text-center text-[17px] leading-relaxed text-[var(--muted)]">
            {c.hero.lead}
          </p>

          {/* Role bar: the demo login is a one-click role pick */}
          <div data-reveal data-reveal-delay="2" className="mx-auto mt-9 flex max-w-2xl flex-wrap items-center justify-center gap-2 rounded-full border border-[var(--line)] bg-white/80 p-1.5 shadow-[0_18px_50px_-30px_oklch(0.3_0.06_195/.5)] backdrop-blur sm:flex-nowrap sm:justify-between sm:pl-4">
            <span className="hidden text-[13px] font-medium text-[var(--muted)] sm:block">{c.hero.tryAs}</span>
            <div className="flex flex-wrap items-center justify-center gap-1">
              {c.hero.roles.map(r => (
                <Link
                  key={r}
                  href="/login"
                  className={`${DEMO_CTA} rounded-full px-3.5 py-2 text-[13.5px] font-medium text-[var(--ink)] transition-colors hover:bg-[var(--teal-soft)]`}
                >
                  {r}
                </Link>
              ))}
            </div>
            <Link
              href="/login"
              className={`${DEMO_CTA} inline-flex h-11 items-center gap-2 rounded-full bg-[var(--teal)] px-5 text-[14px] font-semibold text-white transition-colors hover:bg-[var(--teal-deep)]`}
            >
              {c.hero.cta}
              <ArrowRight className="h-4 w-4" aria-hidden />
            </Link>
          </div>
          <p data-reveal data-reveal-delay="3" className="mt-4 text-center text-[13px] text-[var(--muted)]">
            {c.hero.note}
          </p>
        </div>

        {/* Car + floating file card */}
        <div className="relative mx-auto mt-6 max-w-7xl sm:mt-2">
          <div data-parallax="0.22" className="relative ml-auto w-[150%] max-w-none sm:w-[112%] lg:w-[92%] lg:translate-x-[8%]">
            <img
              src="/site/hero-car.webp"
              alt={c.hero.carAlt}
              width={1376}
              height={768}
              className="site-car-hero block w-full"
              fetchPriority="high"
            />
          </div>
          <div
            data-parallax="-0.16"
            className="absolute bottom-6 left-4 w-[calc(100%-2rem)] max-w-[380px] rounded-2xl border border-white/80 bg-white/95 p-3 shadow-[0_30px_70px_-25px_oklch(0.3_0.06_195/.55)] backdrop-blur sm:bottom-10 sm:left-auto sm:right-8 lg:right-[14%]"
          >
            <div className="flex gap-3">
              <img
                src="/site/car-side.webp"
                alt=""
                aria-hidden
                width={1376}
                height={768}
                className="h-24 w-28 shrink-0 rounded-xl object-cover object-center"
              />
              <div className="min-w-0 flex-1">
                <div className="flex items-baseline justify-between gap-2">
                  <p className="truncate text-[13.5px] font-bold">{c.hero.file.id}</p>
                  <span className="rounded-full bg-[var(--teal-soft)] px-2 py-0.5 text-[10px] font-semibold text-[var(--teal-deep)]">{c.hero.file.step}</span>
                </div>
                <p className="mt-0.5 truncate text-[12px] text-[var(--muted)]">{c.hero.file.desc}</p>
                <dl className="mt-2.5 grid grid-cols-3 gap-2">
                  {c.hero.file.stats.map(([v, l]) => (
                    <div key={l}>
                      <dt className="text-[9.5px] font-semibold uppercase tracking-[0.12em] text-[var(--muted)]">{l}</dt>
                      <dd className="text-[14px] font-bold tabular-nums">{v}</dd>
                    </div>
                  ))}
                </dl>
              </div>
            </div>
            <Link href="/login" className={`${DEMO_CTA} mt-3 flex items-center justify-end gap-1 text-[12.5px] font-semibold text-[var(--teal-deep)] hover:underline`}>
              {c.hero.file.open} <ArrowRight className="h-3.5 w-3.5" aria-hidden />
            </Link>
          </div>
        </div>
      </section>

      {/* How it works */}
      <section id="how" className="scroll-mt-24 bg-[var(--paper-2)] py-20 sm:py-28">
        <div className="mx-auto max-w-6xl px-4 sm:px-6">
          <h2 data-reveal className="max-w-2xl text-3xl font-bold tracking-tight sm:text-[2.6rem] sm:leading-[1.1]">
            {c.how.h2}
          </h2>
          <div className="relative mt-14 grid gap-10 md:grid-cols-3 md:gap-8">
            <div aria-hidden className="absolute left-[16.6%] right-[16.6%] top-7 hidden border-t border-dashed border-[var(--line)] md:block" />
            {c.how.steps.map((s, i) => {
              const Icon = STEP_ICONS[i];
              return (
                <div key={s.t} data-reveal data-reveal-delay={String(i + 1)} className="relative">
                  <span className="relative grid h-14 w-14 place-items-center rounded-full bg-[var(--teal-soft)] text-[var(--teal-deep)]">
                    <Icon className="h-6 w-6" aria-hidden />
                    <span className="absolute -right-1 -top-1 grid h-6 w-6 place-items-center rounded-full bg-[var(--accent)] text-[11px] font-bold text-white">
                      {i + 1}
                    </span>
                  </span>
                  <h3 className="mt-5 text-xl font-bold tracking-tight">{s.t}</h3>
                  <p className="mt-2 max-w-[34ch] text-[15px] leading-relaxed text-[var(--muted)]">{s.d}</p>
                </div>
              );
            })}
          </div>
        </div>
      </section>

      {/* The desk: side car + numbered list */}
      <section id="desk" data-parallax-scope className="relative overflow-hidden py-16 sm:py-24">
        <div className="mx-auto grid max-w-6xl items-center gap-10 px-4 sm:px-6 lg:grid-cols-[1.15fr_1fr] lg:gap-6">
          <div className="relative lg:-ml-24">
            <div data-parallax="0.18">
              <img src="/site/car-side.webp" alt={c.desk.carAlt} width={1376} height={768} loading="lazy" className="site-car-side block w-full" />
            </div>
          </div>
          <div>
            <h2 data-reveal className="text-3xl font-bold tracking-tight sm:text-[2.4rem] sm:leading-[1.1]">
              {c.desk.h2}
            </h2>
            <ul className="mt-8 divide-y divide-[var(--line)]">
              {c.desk.items.map((f, i) => {
                const Icon = DESK_ICONS[i];
                return (
                  <li key={f.t} data-reveal data-reveal-delay={String(i + 1)} className="flex gap-5 py-6 first:pt-0">
                    <span className="mt-0.5 text-[13px] font-bold tabular-nums text-[var(--accent)]">0{i + 1}</span>
                    <span className="grid h-11 w-11 shrink-0 place-items-center rounded-full border border-[var(--line)] bg-white text-[var(--teal-deep)]">
                      <Icon className="h-5 w-5" aria-hidden />
                    </span>
                    <div>
                      <h3 className="text-[17px] font-bold tracking-tight">{f.t}</h3>
                      <p className="mt-1.5 max-w-[42ch] text-[14.5px] leading-relaxed text-[var(--muted)]">{f.d}</p>
                    </div>
                  </li>
                );
              })}
            </ul>
          </div>
        </div>
      </section>

      {/* Screens */}
      <section id="screens" className="scroll-mt-24 bg-[var(--paper-2)] py-20 sm:py-28">
        <div className="mx-auto max-w-6xl px-4 sm:px-6">
          <div className="flex flex-wrap items-end justify-between gap-4">
            <h2 data-reveal className="max-w-xl text-3xl font-bold tracking-tight sm:text-[2.6rem] sm:leading-[1.1]">
              {c.screens.h2}
            </h2>
            <p data-reveal data-reveal-delay="1" className="max-w-sm text-[14.5px] leading-relaxed text-[var(--muted)]">
              {c.screens.p}
            </p>
          </div>
        </div>
        <div className="site-screens mt-10 flex snap-x snap-mandatory gap-5 overflow-x-auto px-4 pb-4 sm:px-6 lg:px-[max(1.5rem,calc((100vw-72rem)/2))]">
          {c.screens.items.map((s, i) => (
            <article
              key={s.tag}
              data-reveal
              data-reveal-delay={String(Math.min(i, 3))}
              className="site-lift w-[82vw] shrink-0 snap-start overflow-hidden rounded-2xl border border-[var(--line)] bg-white sm:w-[420px]"
            >
              <div className="aspect-[8/5] overflow-hidden border-b border-[var(--line)] bg-[var(--paper)]">
                <img src={s.img} alt={`${s.tag} ${c.screens.altSuffix}`} width={3200} height={2000} loading="lazy" className="block h-full w-full object-cover object-top" />
              </div>
              <div className="flex items-start justify-between gap-3 p-4">
                <div>
                  <p className="text-[15px] font-bold tracking-tight">{s.tag}</p>
                  <p className="mt-0.5 text-[13px] leading-snug text-[var(--muted)]">{s.t}</p>
                </div>
                <Link href="/login" aria-label={c.screens.openAriaTpl.replace('{tag}', s.tag)} className={`${DEMO_CTA} grid h-9 w-9 shrink-0 place-items-center rounded-full bg-[var(--teal)] text-white transition-colors hover:bg-[var(--teal-deep)]`}>
                  <ArrowRight className="h-4 w-4" aria-hidden />
                </Link>
              </div>
            </article>
          ))}
        </div>

        <div data-parallax-scope className="mx-auto mt-20 grid max-w-6xl items-center gap-10 px-4 sm:px-6 lg:grid-cols-[1fr_1.35fr]">
          <div>
            <h3 data-reveal className="text-2xl font-bold tracking-tight sm:text-3xl">{c.screens.timelineH3}</h3>
            <ul className="mt-6 space-y-4">
              {c.screens.timeline.map((p, i) => (
                <li key={p} data-reveal data-reveal-delay={String(i + 1)} className="flex items-start gap-3 text-[15px] leading-relaxed text-[var(--muted)]">
                  <Layers className="mt-1 h-4 w-4 shrink-0 text-[var(--teal)]" aria-hidden />
                  {p}
                </li>
              ))}
            </ul>
          </div>
          <div data-reveal>
            <div data-parallax="0.12" className="site-frame overflow-hidden rounded-2xl border border-[var(--line)] bg-white">
              <img src="/site/shots/dossier-detail.webp" alt={c.screens.detailAlt} width={3200} height={2000} loading="lazy" className="block w-full" />
            </div>
          </div>
        </div>
      </section>

      {/* The vehicle: radiating callouts */}
      <section id="vehicle" data-parallax-scope className="relative scroll-mt-24 overflow-hidden py-20 sm:py-28">
        <div aria-hidden className="site-dots pointer-events-none absolute left-[-3rem] top-10 h-64 w-64 opacity-60 [mask-image:radial-gradient(closest-side,#000,transparent)]" />
        <div className="mx-auto max-w-6xl px-4 sm:px-6">
          <h2 data-reveal className="mx-auto max-w-2xl text-center text-3xl font-bold tracking-tight sm:text-[2.6rem] sm:leading-[1.1]">
            {c.vehicle.h2}
          </h2>
          <p data-reveal data-reveal-delay="1" className="mx-auto mt-4 max-w-lg text-center text-[15px] leading-relaxed text-[var(--muted)]">
            {c.vehicle.p}
          </p>

          <div className="mt-14 grid items-center gap-10 lg:grid-cols-[1fr_auto_1fr] lg:gap-0">
            <ul className="space-y-8 lg:space-y-16 lg:pr-14">
              {c.vehicle.left.map((it, i) => {
                const Icon = CALLOUT_LEFT_ICONS[i];
                return (
                  <li key={it.t} data-reveal data-reveal-delay={String(i + 1)} className="site-callout site-callout-l relative flex items-start gap-4 lg:flex-row-reverse lg:text-right">
                    <span className="grid h-11 w-11 shrink-0 place-items-center rounded-full border border-[var(--line)] bg-white text-[var(--teal-deep)]">
                      <Icon className="h-5 w-5" aria-hidden />
                    </span>
                    <div>
                      <p className="text-[15.5px] font-bold tracking-tight">{it.t}</p>
                      <p className="mt-1 text-[13.5px] leading-snug text-[var(--muted)]">{it.d}</p>
                    </div>
                  </li>
                );
              })}
            </ul>
            <div data-parallax="0.14" className="mx-auto w-[240px] sm:w-[280px]">
              <div className="rounded-[2.5rem] bg-white/70 p-6 shadow-[0_40px_80px_-40px_oklch(0.3_0.06_195/.5)] ring-1 ring-[var(--line)]">
                <CarSvgTop zones={{}} onToggleZone={() => {}} className="pointer-events-none" />
              </div>
            </div>
            <ul className="space-y-8 lg:space-y-16 lg:pl-14">
              {c.vehicle.right.map((it, i) => {
                const Icon = CALLOUT_RIGHT_ICONS[i];
                return (
                  <li key={it.t} data-reveal data-reveal-delay={String(i + 1)} className="site-callout site-callout-r relative flex items-start gap-4">
                    <span className="grid h-11 w-11 shrink-0 place-items-center rounded-full border border-[var(--line)] bg-white text-[var(--teal-deep)]">
                      <Icon className="h-5 w-5" aria-hidden />
                    </span>
                    <div>
                      <p className="text-[15.5px] font-bold tracking-tight">{it.t}</p>
                      <p className="mt-1 text-[13.5px] leading-snug text-[var(--muted)]">{it.d}</p>
                    </div>
                  </li>
                );
              })}
            </ul>
          </div>
        </div>
      </section>

      {/* Field app */}
      <section id="field" data-parallax-scope className="scroll-mt-24 bg-[var(--paper-2)] py-20 sm:py-28">
        <div className="mx-auto grid max-w-6xl items-center gap-12 px-4 sm:px-6 lg:grid-cols-[1.1fr_1fr]">
          <div>
            <h2 data-reveal className="text-3xl font-bold tracking-tight sm:text-[2.6rem] sm:leading-[1.1]">
              {c.field.h2}
            </h2>
            <p data-reveal data-reveal-delay="1" className="mt-5 max-w-[52ch] text-[16px] leading-relaxed text-[var(--muted)]">
              {c.field.p}
            </p>
            <div data-reveal data-reveal-delay="2" className="mt-7 flex flex-wrap gap-2">
              {c.field.chips.map((label, i) => {
                const Icon = CHIP_ICONS[i];
                return (
                  <span key={label} className="inline-flex items-center gap-2 rounded-full border border-[var(--line)] bg-white px-3.5 py-2 text-[13px] font-medium">
                    <Icon className="h-4 w-4 text-[var(--teal)]" aria-hidden />
                    {label}
                  </span>
                );
              })}
            </div>
          </div>
          <div data-reveal className="mx-auto w-full max-w-[330px]">
            <div data-parallax="0.2" className="site-frame overflow-hidden rounded-[2.4rem] border-[6px] border-[var(--ink)] bg-[var(--ink)]">
              <img src="/site/shots/mobile-missions.webp" alt={c.field.alt} width={860} height={1800} loading="lazy" className="block w-full rounded-[2rem]" />
            </div>
          </div>
        </div>
      </section>

      {/* Workflow band */}
      <section id="workflow" className="scroll-mt-24 bg-[var(--teal-deep)] py-20 text-white sm:py-28">
        <div className="mx-auto max-w-6xl px-4 sm:px-6">
          <div className="flex flex-wrap items-end justify-between gap-4">
            <h2 data-reveal className="max-w-xl text-3xl font-bold tracking-tight text-white sm:text-[2.6rem] sm:leading-[1.1]">
              {c.workflow.h2}
            </h2>
            <p data-reveal data-reveal-delay="1" className="max-w-sm text-[14.5px] leading-[1.7] text-white/70">
              {c.workflow.p}
            </p>
          </div>
          <ol className="relative mt-14 grid gap-8 sm:grid-cols-2 lg:grid-cols-7 lg:gap-4">
            <div aria-hidden className="absolute left-4 right-4 top-4 hidden border-t border-white/20 lg:block" />
            {c.workflow.steps.map((w, i) => (
              <li key={w.t} data-reveal data-reveal-delay={String(Math.min(i % 4, 3))} className="relative">
                <span className="relative z-10 grid h-8 w-8 place-items-center rounded-full bg-white text-[13px] font-bold text-[var(--teal-deep)]">
                  {i + 1}
                </span>
                <h3 className="mt-4 text-[15px] font-bold tracking-tight text-white">{w.t}</h3>
                <p className="mt-1 text-[13px] leading-[1.6] text-white/70">{w.d}</p>
              </li>
            ))}
          </ol>
        </div>
      </section>

      {/* Split contact banner */}
      <section className="py-20 sm:py-28">
        <div className="mx-auto max-w-6xl px-4 sm:px-6">
          <h2 data-reveal className="mx-auto max-w-2xl text-center text-3xl font-bold tracking-tight sm:text-[2.6rem] sm:leading-[1.1]">
            {c.banner.h2a}{' '}
            <span className="whitespace-nowrap font-normal text-[var(--accent)]" style={{ fontFamily: SCRIPT, fontSize: '1.3em', lineHeight: 1 }}>
              {c.banner.accent}
            </span>{' '}
            {c.banner.h2b}
          </h2>
          <div data-reveal data-reveal-delay="1" className="relative mx-auto mt-12 grid max-w-4xl gap-4 md:grid-cols-2 md:gap-0">
            <div className="rounded-3xl bg-[var(--teal)] p-8 text-white md:rounded-r-none md:pr-14">
              <p className="text-[12px] font-semibold uppercase tracking-[0.14em] text-white/70">{c.banner.eyebrowLeft}</p>
              <p className="mt-2 text-2xl font-bold tracking-tight">{c.banner.titleLeft}</p>
              <p className="mt-2 max-w-[38ch] text-[14.5px] leading-relaxed text-white/80">{c.banner.pLeft}</p>
              <Link href="/login" className={`${DEMO_CTA} mt-6 inline-flex h-11 items-center gap-2 rounded-full bg-white px-5 text-[14px] font-semibold text-[var(--teal-deep)] transition-colors hover:bg-[var(--teal-soft)]`}>
                {c.banner.cta}
                <ArrowRight className="h-4 w-4" aria-hidden />
              </Link>
              <p className="mt-4 text-[13px] text-white/75">
                {c.banner.prefer}{' '}
                <Link href={c.paths.contact} className="font-semibold text-white underline-offset-2 hover:underline">{c.banner.book}</Link>{' '}
                {c.banner.or} <Link href={c.paths.faq} className="font-semibold text-white underline-offset-2 hover:underline">{c.banner.faq}</Link>.
              </p>
            </div>
            <div className="rounded-3xl bg-[var(--teal-deep)] p-8 text-white md:rounded-l-none md:pl-14">
              <p className="text-[12px] font-semibold uppercase tracking-[0.14em] text-white/70">{c.banner.eyebrowRight}</p>
              <ol className="mt-4 space-y-3 text-[14.5px] leading-relaxed text-white/85">
                {c.banner.list.map((t, i) => (
                  <li key={t} className="flex gap-3">
                    <span className="mt-0.5 text-[12px] font-bold tabular-nums text-white/60">0{i + 1}</span>
                    <span>{t}</span>
                  </li>
                ))}
              </ol>
            </div>
          </div>
        </div>
      </section>

      {/* Trust */}
      <section id="security" className="scroll-mt-24 border-t border-[var(--line)] bg-[var(--paper-2)] py-20 sm:py-24">
        <div className="mx-auto grid max-w-6xl gap-10 px-4 sm:px-6 lg:grid-cols-[1fr_2fr]">
          <div>
            <h2 data-reveal className="text-3xl font-bold tracking-tight sm:text-[2.4rem] sm:leading-[1.1]">
              {c.trust.h2}
            </h2>
            <p data-reveal data-reveal-delay="1" className="mt-4 max-w-[36ch] text-[14.5px] leading-relaxed text-[var(--muted)]">
              {c.trust.more1}{' '}
              <Link href={c.paths.secFaq} className="font-semibold text-[var(--teal-deep)] hover:underline">{c.trust.secFaq}</Link>
              {c.trust.more2}{' '}
              <Link href={c.paths.about} className="font-semibold text-[var(--teal-deep)] hover:underline">{c.trust.about}</Link>
              {c.trust.more3}
            </p>
          </div>
          <dl className="grid gap-x-10 sm:grid-cols-2">
            {c.trust.items.map((t, i) => {
              const Icon = TRUST_ICONS[i];
              return (
                <div key={t.t} data-reveal data-reveal-delay={String((i % 2) + 1)} className="border-t border-[var(--line)] py-6">
                  <dt className="flex items-center gap-2.5 text-[16px] font-bold tracking-tight">
                    <Icon className="h-5 w-5 text-[var(--teal)]" aria-hidden />
                    {t.t}
                  </dt>
                  <dd className="mt-2 max-w-[40ch] text-[14.5px] leading-relaxed text-[var(--muted)]">{t.d}</dd>
                </div>
              );
            })}
          </dl>
        </div>
      </section>
    </main>
  );
}
