import type { Metadata, Viewport } from 'next';
import { Outfit } from 'next/font/google';
import './globals.css';
import { Toaster } from '@/components/ui/toaster';
import { cn } from '@/lib/utils';
import { FirebaseClientProvider } from '@/firebase/client-provider';
import { ThemeProvider } from '@/components/theme-provider';
import { PwaRegister } from '@/components/pwa-register';
import { LocaleProvider } from '@/i18n';
import { BRAND } from '@/lib/brand';

const outfit = Outfit({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
  variable: '--font-outfit',
  display: 'swap',
});

export const metadata: Metadata = {
  title: BRAND.productName,
  description: BRAND.appDescription,
  manifest: '/manifest.webmanifest',
  appleWebApp: {
    capable: true,
    statusBarStyle: 'default',
    title: BRAND.shortName,
  },
  icons: {
    icon: [
      // Brand-scoped favicon (generated by scripts/generate-demo-favicon.mjs).
      { url: BRAND.id === 'demo' ? `${BRAND.iconsPath}/favicon.ico` : '/favicon.ico', sizes: '48x48' },
      { url: `${BRAND.iconsPath}/icon-192.png`, sizes: '192x192', type: 'image/png' },
      { url: `${BRAND.iconsPath}/icon-512.png`, sizes: '512x512', type: 'image/png' },
    ],
    apple: `${BRAND.iconsPath}/apple-touch-icon.png`,
  },
};

export const viewport: Viewport = {
  width: 'device-width',
  initialScale: 1,
  maximumScale: 5,
  themeColor: '#0f766e',
  // Let the app draw under the status bar / display cutout area when
  // running in fullscreen PWA mode. Combine with safe-area CSS inset
  // padding where needed.
  viewportFit: 'cover',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang={BRAND.defaultLocale} suppressHydrationWarning className={outfit.variable}>
      <body className={cn('font-body antialiased')}>
        <ThemeProvider attribute="class" defaultTheme="light" enableSystem={false}>
          <LocaleProvider>
            <FirebaseClientProvider>
              <PwaRegister />
              {children}
              <Toaster />
            </FirebaseClientProvider>
          </LocaleProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
